name: Build and push image to ECR

on:
  workflow_call:
    inputs:
      awsRegion:
        type: string
        required: false
        default: eu-west-1
      ecrRepositoryName:
        type: string
        required: true
      directoryPath:
        type: string
        required: true
      imageTag:
        type: string
        required: false
        default: latest
    secrets:
      awsAccessKeyId:
        required: true
      awsSecretKey:
        required: true
      dockerHubUsername:
        required: true
      dockerHubAccessToken:
        required: true

defaults:
  run:
    shell: bash

jobs:
  buildAndPushImage:
    name: Build and push image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretKey }}
          aws-region: ${{ inputs.awsRegion }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerHubUsername }}
          password: ${{ secrets.dockerHubAccessToken }}

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ${{ inputs.directoryPath }}
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrRepositoryName }}:${{ inputs.imageTag }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrRepositoryName }}:${{ inputs.imageTag }}
