name: Deploy server

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - servers/server/**

defaults:
  run:
    shell: bash

jobs:
  buildAndPushImage:
    uses: maxsynnott/pixel-grid/.github/workflows/buildAndPushImage.yml@master
    with:
      ecrRepositoryName: node-server
      directoryPath: ./servers/server
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
      dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
      dockerHubAccessToken: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
