name: Terraform apply

on:
  workflow_call:
    inputs:
      awsRegion:
        type: string
        required: false
        default: eu-west-1
      target:
        type: string
        required: false
    secrets:
      awsAccessKeyId:
        required: true
      awsSecretKey:
        required: true

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  terraformApply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretKey }}
          aws-region: ${{ inputs.awsRegion }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve ${{ inputs.target && format('-target={0}', inputs.target) || '' }}
